---
specfile_path: libnbd.spec
upstream_package_name: libnbd
downstream_package_name: libnbd
actions:
  post-upstream-clone:
  - autoreconf -i
  - ./configure
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
