---
- name: Provision environment with dependncies to run libnbd's test suite
  hosts: all
  tasks:
  - name: install all builddeps defined in latest Fedora libnbd
    command: dnf -y builddep libnbd
    become: true
  - name: install auto* packages
    dnf:
      name:
      - autoconf
      - automake
      - libtool
    become: true
  - name: run autoreconf
    command: autoreconf -i
    args:
      chdir: ~/git-source
  - name: run ./configure
    command: ./configure --disable-dependency-tracking
    args:
      chdir: ~/git-source
  - name: install build deps for libnbd defined in upstream spec
    command: dnf -y builddep --spec ./libnbd.spec
    become: true
    args:
      chdir: ~/git-source

